    save_best: True
    plot_agents: False

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./td3_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 1
      n_envs: 20
      n_steps: 1
      buffer_size: 10e6
      tau_target: 0.09
      n_updates: 6
      eval_interval: 2500
      learning_starts: 10000
      nb_evals: 1
      max_grad_norm: 0.5
      batch_size: 200
      max_epochs: 990000
      action_noise: 0.1
      discount_factor: 1.0
      architecture:
        actor_hidden_size: [207, 207]
        critic_hidden_size: [256, 256]

    gym_env:
      classname: __main__.make_gym_env
      env_name: Swimmer-v3

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 0.0002
    
    critic_optimizer:
      classname: torch.optim.Adam
      lr: 0.001
