    save_best: True
    plot_agents: True

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./ppo_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 4
      nb_seeds: 1
      max_grad_norm: 0.5
      n_envs: 8
      n_steps: 20
      eval_interval: 2000
      nb_evals: 10
      gae: 0.9
      max_epochs: 8000
      beta: 0.1
      discount_factor: 0.95
      clip_range: 0.2
      clip_range_vf: 0
      entropy_coef: 2e-7
      critic_coef: 0.4
      policy_coef: 1
      opt_epochs: 3
      batch_size: 16
      architecture:
        policy_hidden_size: [256, 256]
        critic_hidden_size: [256, 256]

    gym_env:
      classname: __main__.make_gym_env
      env_name: LunarLander-v2

    optimizer:
      classname: torch.optim.Adam
      lr: 0.0003
